import React from 'react';
// @ts-ignore
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 30, borderBottom: 2, borderBottomColor: '#4f46e5', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e1b4b' },
  subtitle: { fontSize: 12, color: '#4b5563', marginTop: 4 },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 5, color: '#4f46e5', textTransform: 'uppercase' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 4 },
  label: { width: 150, fontSize: 10, color: '#6b7280' },
  value: { flex: 1, fontSize: 11, color: '#111827', fontWeight: 'bold' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 8, borderBottomWidth: 1, borderBottomColor: '#d1d5db', marginTop: 5 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', padding: 6 },
  tableCellTitle: { flex: 2, fontSize: 10, color: '#4b5563', fontWeight: 'bold' },
  tableCell: { flex: 1, fontSize: 10, color: '#4b5563', textAlign: 'center' },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5, gap: 4 },
  gridItem: { width: 25, height: 18, borderWidth: 1, borderColor: '#e5e7eb', justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  gridTextNum: { fontSize: 6, color: '#6b7280', marginRight: 2 },
  gridTextValCorrect: { fontSize: 7, color: '#15803d', fontWeight: 'bold' },
  gridTextValWrong: { fontSize: 7, color: '#b91c1c', fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#f3f4f6', paddingTop: 10 }
});

export const BakumReport = ({ data, user }: { data: any, user: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Psychological Report</Text>
        <Text style={styles.subtitle}>Test Category: Bakat Umum (BAKUM)</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Participant Information</Text>
        <View style={styles.row}><Text style={styles.label}>Full Name</Text><Text style={styles.value}>{user.fullName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Email Address</Text><Text style={styles.value}>{user.email}</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Detailed Breakdown (Persoalan 2 - 10)</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.tableCellTitle}>Bagian / Persoalan</Text>
          <Text style={styles.tableCell}>Correct</Text>
          <Text style={styles.tableCell}>Total</Text>
          <Text style={styles.tableCell}>Score</Text>
          <Text style={styles.tableCell}>Category</Text>
        </View>
        {Object.entries(data.persoalan_results || {}).map(([key, val]: any) => (
          <View style={styles.tableRow} key={key}>
            <Text style={styles.tableCellTitle}>{key.replace('_', ' ').toUpperCase()}</Text>
            <Text style={styles.tableCell}>{val.correct}</Text>
            <Text style={styles.tableCell}>{val.total}</Text>
            <Text style={{ flex: 1, fontSize: 10, color: '#111827', textAlign: 'center', fontWeight: 'bold' }}>{val.score}</Text>
            <Text style={{ flex: 1, fontSize: 10, textAlign: 'center', color: val.category === 'tinggi' ? '#15803d' : val.category === 'sedang' ? '#ca8a04' : '#b91c1c' }}>{val.category.toUpperCase()}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem.</Text>
    </Page>
    
    {/* Page 2 for Item Analysis */}
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Item Analysis (BAKUM)</Text>
      </View>
      {Object.entries(data.itemAnalysis || {}).map(([key, arr]: any) => (
        <View style={styles.section} key={key}>
          <Text style={styles.sectionTitle}>{key.replace('_', ' ').toUpperCase()}</Text>
          <View style={styles.gridContainer}>
            {arr.map((isCorrect: boolean, index: number) => (
              <View style={styles.gridItem} key={index}>
                <Text style={styles.gridTextNum}>{index + 1}.</Text>
                <Text style={isCorrect ? styles.gridTextValCorrect : styles.gridTextValWrong}>{isCorrect ? 'V' : 'X'}</Text>
              </View>
            ))}
          </View>
        </View>
      ))}
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem.</Text>
    </Page>
  </Document>
);
