/* 
  NOTE: This requires @react-pdf/renderer 
  Run: npm install @react-pdf/renderer
*/

import React from 'react';
// @ts-ignore
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#4f46e5',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1e1b4b',
  },
  subtitle: {
    fontSize: 12,
    color: '#4b5563',
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#4f46e5',
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    paddingVertical: 8,
  },
  label: {
    width: 150,
    fontSize: 10,
    color: '#6b7280',
  },
  value: {
    flex: 1,
    fontSize: 11,
    color: '#111827',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#9ca3af',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    paddingTop: 10,
  }
});

export const CFITReport = ({ data, user }: { data: any, user: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Psychological Report</Text>
        <Text style={styles.subtitle}>Test Category: Culture Fair Intelligence Test (CFIT)</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Participant Information</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Full Name</Text>
          <Text style={styles.value}>{user.fullName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Email Address</Text>
          <Text style={styles.value}>{user.email}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Test Date</Text>
          <Text style={styles.value}>{new Date().toLocaleDateString()}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Test Results</Text>
        <View style={styles.row}>
          <Text style={styles.label}>IQ Score</Text>
          <Text style={styles.value}>{data.iqScore || 'Calculating...'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Classification</Text>
          <Text style={styles.value}>{data.classification || 'N/A'}</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        This report is automatically generated by Mascons Ecosystem. 
        Confidential for authorized personnel only.
      </Text>
    </Page>
  </Document>
);
