import React from 'react';
// @ts-ignore
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 30, borderBottom: 2, borderBottomColor: '#4f46e5', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e1b4b' },
  subtitle: { fontSize: 12, color: '#4b5563', marginTop: 4 },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 5, color: '#4f46e5', textTransform: 'uppercase' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 4 },
  label: { width: 150, fontSize: 10, color: '#6b7280' },
  value: { flex: 1, fontSize: 11, color: '#111827', fontWeight: 'bold' },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5, gap: 4 },
  gridItem: { width: 30, height: 20, borderWidth: 1, borderColor: '#e5e7eb', justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  gridTextNum: { fontSize: 7, color: '#6b7280', marginRight: 2 },
  gridTextValCorrect: { fontSize: 7, color: '#15803d', fontWeight: 'bold' },
  gridTextValWrong: { fontSize: 7, color: '#b91c1c', fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#f3f4f6', paddingTop: 10 }
});

export const InteligensiUmumReport = ({ data, user }: { data: any, user: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Psychological Report</Text>
        <Text style={styles.subtitle}>Test Category: Inteligensi Umum</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Participant Information</Text>
        <View style={styles.row}><Text style={styles.label}>Full Name</Text><Text style={styles.value}>{user.fullName}</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Results Summary</Text>
        <View style={styles.row}><Text style={styles.label}>Total Questions</Text><Text style={styles.value}>{data.score?.total}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Final Score Percentage</Text><Text style={styles.value}>{data.score?.percentage.toFixed(2)}%</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Item Analysis (100 Questions)</Text>
        <View style={styles.gridContainer}>
          {(data.itemAnalysis || []).map((isCorrect: boolean, index: number) => (
            <View style={styles.gridItem} key={index}>
              <Text style={styles.gridTextNum}>{index + 1}.</Text>
              <Text style={isCorrect ? styles.gridTextValCorrect : styles.gridTextValWrong}>{isCorrect ? 'V' : 'X'}</Text>
            </View>
          ))}
        </View>
      </View>
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem.</Text>
    </Page>
  </Document>
);
