import React from 'react';
// @ts-ignore
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 30, borderBottom: 2, borderBottomColor: '#4f46e5', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e1b4b' },
  subtitle: { fontSize: 12, color: '#4b5563', marginTop: 4 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 10, color: '#4f46e5', textTransform: 'uppercase' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 8 },
  label: { width: 150, fontSize: 10, color: '#6b7280' },
  value: { flex: 1, fontSize: 11, color: '#111827', fontWeight: 'bold' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 8, borderBottomWidth: 1, borderBottomColor: '#d1d5db', marginTop: 10 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', padding: 8 },
  tableCellTitle: { flex: 1, fontSize: 10, color: '#4b5563', fontWeight: 'bold' },
  tableCell: { flex: 1, fontSize: 10, color: '#4b5563', textAlign: 'center' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#f3f4f6', paddingTop: 10 }
});

export const KraepelinReport = ({ data, user }: { data: any, user: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Psychological Report</Text>
        <Text style={styles.subtitle}>Test Category: Kraepelin</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Participant Information</Text>
        <View style={styles.row}><Text style={styles.label}>Full Name</Text><Text style={styles.value}>{user.fullName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Email Address</Text><Text style={styles.value}>{user.email}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Test Date</Text><Text style={styles.value}>{new Date().toLocaleDateString()}</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Results Summary</Text>
        <View style={styles.row}><Text style={styles.label}>Total Attempted</Text><Text style={styles.value}>{data.score?.total}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Final Accuracy Percentage</Text><Text style={styles.value}>{data.score?.percentage.toFixed(2)}%</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Interpretative Analysis</Text>
        <View style={styles.row}><Text style={styles.label}>Kecepatan Kerja (Pace/Puncak)</Text><Text style={styles.value}>{data.analysis?.puncak}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Rata-Rata Kecepatan</Text><Text style={styles.value}>{data.analysis?.rata_rata}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Ketahanan (Endurance)</Text><Text style={styles.value}>{data.analysis?.ketahanan}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Keajegan (Steadiness)</Text><Text style={styles.value}>{data.analysis?.stabilitas}</Text></View>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Column Breakdown</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.tableCellTitle}>Column</Text>
          <Text style={styles.tableCell}>Work Pace</Text>
          <Text style={styles.tableCell}>Correct</Text>
          <Text style={styles.tableCell}>Wrong</Text>
        </View>
        {(data.columns || []).map((col: any) => (
          <View style={styles.tableRow} key={col.colNumber}>
            <Text style={styles.tableCellTitle}>Col {col.colNumber}</Text>
            <Text style={styles.tableCell}>{col.pace}</Text>
            <Text style={styles.tableCell}>{col.correct}</Text>
            <Text style={styles.tableCell}>{col.wrong}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem. Confidential for authorized personnel only.</Text>
    </Page>
  </Document>
);
