import React from 'react';
// @ts-ignore
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 30, borderBottom: 2, borderBottomColor: '#4f46e5', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e1b4b' },
  subtitle: { fontSize: 12, color: '#4b5563', marginTop: 4 },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 5, color: '#4f46e5', textTransform: 'uppercase' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 4 },
  label: { width: 150, fontSize: 10, color: '#6b7280' },
  value: { flex: 1, fontSize: 11, color: '#111827', fontWeight: 'bold' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: 8, borderBottomWidth: 1, borderBottomColor: '#d1d5db', marginTop: 5 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', padding: 6 },
  tableCellTitle: { flex: 2, fontSize: 10, color: '#4b5563', fontWeight: 'bold' },
  tableCell: { flex: 1, fontSize: 10, color: '#4b5563', textAlign: 'center' },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5, gap: 4 },
  gridItem: { width: 30, height: 20, borderWidth: 1, borderColor: '#e5e7eb', justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  gridTextNum: { fontSize: 7, color: '#6b7280', marginRight: 2 },
  gridTextVal: { fontSize: 8, color: '#2563eb', fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#f3f4f6', paddingTop: 10 }
});

const bidangMinatNames: any = {
  'A': 'Pribadi Sosial', 'B': 'Natural', 'C': 'Mekanik', 'D': 'Bisnis',
  'E': 'Seni', 'F': 'Sains', 'G': 'Kepemimpinan', 'H': 'Sosial',
  'I': 'Bahasa', 'J': 'Numerik', 'K': 'Spasial', 'L': 'Klerikal'
};

export const MinatJabatanReport = ({ data, user }: { data: any, user: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Psychological Report</Text>
        <Text style={styles.subtitle}>Test Category: Minat Jabatan</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Participant Information</Text>
        <View style={styles.row}><Text style={styles.label}>Full Name</Text><Text style={styles.value}>{user.fullName}</Text></View>
      </View>
      
      {/* 1. Bidang Minat */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>1. Bidang Minat Analysis</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.tableCellTitle}>Bidang Minat (Kode)</Text>
          <Text style={styles.tableCell}>Score</Text>
          <Text style={styles.tableCell}>Category</Text>
        </View>
        {Object.entries(data.bidangMinatKategori || {}).map(([key, val]: any) => (
          <View style={styles.tableRow} key={key}>
            <Text style={styles.tableCellTitle}>{bidangMinatNames[key] || key} ({key})</Text>
            <Text style={styles.tableCell}>{data.bidangMinatScore[key]}</Text>
            <Text style={{ flex: 1, fontSize: 10, textAlign: 'center', fontWeight: 'bold', color: val.includes('Sangat') ? '#15803d' : '#ca8a04' }}>{val}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem.</Text>
    </Page>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Item Analysis (Minat Jabatan)</Text>
      </View>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>120 Questions Detail</Text>
        <View style={styles.gridContainer}>
          {(data.itemAnalysis || []).map((ans: string, index: number) => (
            <View style={styles.gridItem} key={index}>
              <Text style={styles.gridTextNum}>{index + 1}.</Text>
              <Text style={styles.gridTextVal}>{ans}</Text>
            </View>
          ))}
        </View>
      </View>
      <Text style={styles.footer}>This report is automatically generated by Mascons Ecosystem.</Text>
    </Page>
  </Document>
);
